export const Users = [
  {
    id: 1,
    profilePicture: "01.jpg",
    username: "Qodirov Dilmurod",
  },
  {
    id: 2,
    profilePicture: "02.jpg",
    username: "Duschanov Jasorat",
  },
  {
    id: 3,
    profilePicture: "03.jpg",
    username: "Matyakubov Jamol",
  },
  {
    id: 4,
    profilePicture: "04.jpg",
    username: "Sadullayev Jahongir",
  },
  {
    id: 5,
    profilePicture: "05.jpg",
    username: "Tajimurotov Sanjar",
  },
  {
    id: 6,
    profilePicture: "06.jpg",
    username: "Karayev Oybek",
  },
  {
    id: 7,
    profilePicture: "07.jpg",
    username: "Gulimov Mamurjon",
  },
  {
    id: 8,
    profilePicture: "08.jpg",
    username: "Xayitboyev Ruslan",
  },
  {
    id: 9,
    profilePicture: "09.jpg",
    username: "Nurimmataov Akbar",
  },
  {
    id: 10,
    profilePicture: "10.jpg",
    username: "Bekmurotov Rasul",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/01.png",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/02.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/03.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/04.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/05.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/06.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/07.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/08.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/09.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
